# Generated by Django 5.2.8 on 2026-05-05 01:11

import resume_fixer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_fixer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to=resume_fixer.models.resume_upload_path),
        ),
    ]
