# Generated by Django 5.2.8 on 2026-05-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_fixer', '0003_skill_alias_and_esco_lengths'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skillalias',
            new_name='resume_fixe_normali_7d7d00_idx',
            old_name='resume_fixe_normali_0d5be3_idx',
        ),
    ]
